apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: sso
spec:
  selector:
    app: frontend
  ports:
  - protocol: TCP
    port: 3000
    targetPort: 3000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
  namespace: sso
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend-container
        image: clemme/frontend
        env:
        - name: REACT_APP_MIDDLEWARE_URL
          value: "http://localhost:8082"
        - name: REACT_APP_METASTORE
          value: "http://localhost:4000"
        - name: REACT_APP_METASTORE_URL
          value: "http://localhost:4000"
        - name: REACT_APP_DATAEXPLORER_URL
          value: "http://localhost:8086"
        ports:
        - containerPort: 3000
