apiVersion: v1
kind: Pod
metadata:
  name: mqtt-broker
  labels: 
    app: mqtt-broker
spec:
  containers:
  - name: mqtt-broker
    image: hivemq/hivemq-ce
    ports:
    - containerPort: 1883
      name: mqtt
    - containerPort: 9001
      name: mqtt-websockets
---
apiVersion: v1
kind: Service
metadata:
  name: mqtt-broker
spec:
  type: NodePort
  ports:
  - name: tcp
    nodePort: 30950
    port: 1883
  selector:
    app: mqtt-broker