version: '3'
services:
  mosquitto:
    image: eclipse-mosquitto
    ports:
      - 1883:1883
    volumes:
      - ./mosquitto.conf:/mosquitto/config/mosquitto.conf
    profiles:
      - broker
  # producer:
  #   build: .
  #   depends_on:
  #     - mosquitto
  #   environment:
  #     - HOST=mosquitto
  #     - PORT=1883
  #   profiles:
  #     - producer