kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
# name: kafka
nodes:
- role: control-plane
  extraPortMappings:
  - containerPort: 80
    hostPort: 8080
    protocol: TCP
  - containerPort: 443
    hostPort: 8443
    protocol: TCP
  - containerPort: 30950
    hostPort: 8088
    protocol: TCP
    listenAddress: "127.0.0.1"
