name: Build Data Explorer

on:
  push:
    branches:
      # - main
      - 'feature/data-explorer**'
    tags:
      - "data-explorer/v*.*.*"
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    env: 
      working-directory: ./data_explorer/DataExplorer/
    
    defaults:
      run:
        working-directory: ${{ env.working-directory }}
    
    steps:
    - 
      uses: actions/checkout@v3
    -
      name: Docker meta
      id: meta
      uses: docker/metadata-action@v4
      with:
        # list of Docker images to use as base name for tags
        images: |
          clemme/data-explorer
        # generate Docker tags based on the following events/attributes
        # match the tag format "data-explorer/v1.0.0" and extracting the version number
        # and use the branch name as tag
        # use the latest tag
        tags: |
          type=match,pattern=data-explorer/v(\d.\d.\d),group=1
          type=ref,event=branch 
        flavor: |
          latest=true
    -
      name: Set up QEMU
      uses: docker/setup-qemu-action@v2
    -
      name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    -
      name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    -
      name: Build and push
      uses: docker/build-push-action@v4
      with:
        context: ${{ env.working-directory }}
        push: true
        platforms: linux/amd64,linux/arm64
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
        cache-from: type=gha
        cache-to: type=gha,mode=max
