name: Build Ingress Adapter

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    env: 
      working-directory: ./ingress_adapter/IngressAdapter/
    
    defaults:
      run:
        working-directory: ${{ env.working-directory }}
    
    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file ./IngressAdapter/Dockerfile --tag ingress-adapter:$(date +%s)
